name: ci

on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "v*.*.*"

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm
      - run: pnpm ci
      - run: pnpm lint
      - run: pnpm format:check
      - run: pnpm types:check
      - run: pnpm build
      - name: deploy to github pages
        if: github.ref == 'refs/heads/main'
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages
          folder: dist
